# Generated by Django 4.1.7 on 2023-03-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAndReviews', '0003_alter_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='review',
        ),
    ]
