# Generated by Django 4.1.7 on 2023-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAndReviews', '0007_alter_product_description_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=400),
        ),
    ]
