# Generated by Django 4.1.7 on 2023-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAndReviews', '0011_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='attribute',
            field=models.CharField(max_length=50),
        ),
    ]
