# Generated by Django 4.1.7 on 2023-03-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAndReviews', '0012_info_value_alter_info_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
